name: Build and Test Java Project

on:
  push:
    branches:
      - dev
      - testing

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn install

      - name: Run tests
        run: mvn test